name: htmltopdf-build

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build the Docker image
        run: docker build -f Dockerfile -t ghcr.io/matbyte-com/htmltopdf-api:${GITHUB_REF_NAME} .

      - name: Push to GitHub registry
        run: docker push ghcr.io/matbyte-com/htmltopdf-api:${GITHUB_REF_NAME}
